### ISSUE TITLE
Миксин `text-shorten`

### ISSUE THREAD

**Issue by rx1310** [91muilak/kalium19#24]
Надо добавить миксин `text-shorten`:
```scss
@mixin text-shorten {
   overflow: hidden;
   text-overflow: ellipsis;
   white-space: nowrap;
}
```

**Comment by rx1310** [comment]
Или лучше использовать этот вариант:

```scss
@mixin text-shorten($numLines: 1) {
  white-space: nowrap;
  text-overflow: ellipsis;
  overflow: hidden;
 
  @supports (-webkit-line-clamp: $numLines) {
    overflow: hidden;
    text-overflow: ellipsis;
    white-space: initial;
    display: -webkit-box;
    -webkit-line-clamp: $numLines;
    -webkit-box-orient: vertical;
  }
}
```
