### ISSUE TITLE
Миксин `vertical-center`

### ISSUE THREAD

**Issue by rx1310** [91muilak/kalium19#27]
Надо добавить миксин `vertical-center`для вертикального центрирования:

```scss
@mixin vertical-center {
   position: relative;
   top: 50%;
   transform: translateY(-50%);
}
```

**Comment by rx1310** [comment]
Или такой миксин, который я взял с этого [сайта](https://www.toptal.com/css/sass-mixins-keep-your-stylesheets-dry):
```scss
@mixin center($position) {
  position: absolute;
  
  @if $position == 'vertical' {
    top: 50%;
    -webkit-transform: translateY(-50%);
    -ms-transform: translateY(-50%);
    transform: translateY(-50%);
  }
  @else if $position == 'horizontal' {
    left: 50%;
    -webkit-transform: translateX(-50%);
    -ms-transform: translateX(-50%);
    transform: translate(-50%);
  }
  @else if $position == 'both' {
    top: 50%;
    left: 50%;
    -webkit-transform: translate(-50%, -50%);
    -ms-transform: translate(-50%, -50%);
    transform: translate(-50%, -50%);
  }
}
```
