### ISSUE TITLE
Миксин `z-index`

### ISSUE THREAD

**Issue by rx1310** [91muilak/kalium19#41]
**Задачи:**
- [ ] 1: Добавить миксин для автоматического присваивания значения свойству `z-index` по отсортированной карте SASS

**Пример задачи 1**
```scss
$z_indexes: (
  "nav",
  "header",
  ...
);

.nav {
  @include z-index("nav");
}

.header {
  @include z-index("header");
}
```
```css
.nav {
  z-index: 1;
}

.header {
  z-index: 2;
}
```

[Пример миксина](https://engageinteractive.co.uk/blog/top-10-scss-mixins)
