### ISSUE TITLE
Миксин `reset-list`

### ISSUE THREAD

**Issue by rx1310** [91muilak/kalium19#42]
**Задача:**
- [ ] Добавить миксин для сброса базовых стилей списков

**Предварительная версия решения:**
```scss
@mixin reset-list() {
    margin: 0;
    padding: 0;
    list-style: none;
}
```
